name: aria_env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1.0
  - pip:
      - projectaria-tools